package com.smartg.jdbc;

public enum SQL_ParamType {
	STRING, INT, LONG, ARRAY, ASCII_STREAM, BIG_DECIMAL, BINARY_STREAM, BLOB, BLOB_STREAM, BOOLEAN, BYTE, BYTES, CHAR_STREAM, CLOB, CLOB_STREAM, DATE, DOUBLE, FLOAT, N_CHAR_STREAM, N_CLOB, N_CLOB_STREAM, N_STRING, OBJECT, REF, ROWID, SHORT, SQL_XML, TIME, TIMESTAMP, UNICODE_STREAM, URL;
}
